"""init

Revision ID: 9af1bd744e94
Revises: 
Create Date: 2023-07-22 03:06:54.320673

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '9af1bd744e94'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Avatar',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('src', sa.String(), nullable=False),
                    sa.Column('alt', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_Avatar_id'), 'Avatar', ['id'], unique=False)
    
    op.create_table('User',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('username', sa.String(), nullable=True),
                    sa.Column('first_name', sa.String(), nullable=False),
                    sa.Column('last_name', sa.String(), nullable=False),
                    sa.Column('phone', sa.String(length=20), nullable=False),
                    sa.Column('sex', sa.Enum('MAN', 'WOMAN', name='sexenum'), nullable=False),
                    sa.Column('avatar_id', sa.Integer(), nullable=True),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(['avatar_id'], ['Avatar.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_User_id'), 'User', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_User_id'), table_name='User')
    op.drop_table('User')
    op.drop_index(op.f('ix_Avatar_id'), table_name='Avatar')
    op.drop_table('Avatar')
    # ### end Alembic commands ###
