"""User.sex nullable changed

Revision ID: b58364b073a7
Revises: e3b673eb67c3
Create Date: 2023-07-23 21:49:57.794989

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b58364b073a7'
down_revision = 'e3b673eb67c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'sex',
               existing_type=postgresql.ENUM('Man', 'Woman', name='sexenum'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'sex',
               existing_type=postgresql.ENUM('Man', 'Woman', name='sexenum'),
               nullable=False)
    # ### end Alembic commands ###
